dist: trusty
sudo: required

services:
  - postgresql
addons:
    postgresql: "9.5"
    apt:
      packages:
        - postgresql-9.5-postgis-2.3
    sonarqube:
        branches:
          - master
before_script:
  - psql -U postgres -c "create user socializa password 'socializa'"
  - psql -U postgres -c "create database test_socializa owner socializa"
  - psql -U postgres -d test_socializa -c "create extension postgis"
language: python
python:
  - "3.4"
install:
  - pip install -r backend/requirements.txt
  - pip install coveralls
script:
  - cd backend
  - pylint -f parseable --ignore-patterns="env/" * | tee pylint.out
  - ￼￼coverage run --source='.' manage.py test --keepdb
  - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  - coverage xml
  - cd ..
  - sonar-scanner
after_success: coveralls
